### ISSUE TITLE
Player not working on Android 4.1, 4.2, 4.3

### ISSUE THREAD

**Issue by BartoszJarocki** [kaltura/player-sdk-native-android#103]
Version used:  **v2.3.0.rc4**
Environment: **Galaxy Nexus, Android 4.3**, **Galaxy Core Prime, Android 4.2.2**
Steps to reproduce: **start player**

Player keeps logging and never starts: 
`02-16 15:12:06.156 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.226 25748-25748/* E/Web Console: Uncaught Error: Error calling method on NPObject. at null:1
02-16 15:12:06.234 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.265 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.367 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.468 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.539 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.609 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.648 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.679 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.750 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.836 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:06.906 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!
02-16 15:12:07.008 25748-25748/* W/PicturePileLayerContent: Warning: painting PicturePile without content!`

sometimes:
`02-16 14:23:02.882 1004-1004/* I/Web Console: flavorsListChanged at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:02.882 1004-1004/* I/Web Console: null at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:02.882 1004-1004/* W/Web Console: The page at about:blank displayed insecure content from js-frame:flavorsListChanged:0:%5B%5D.
                                                                       at null:1
02-16 14:23:02.930 1004-1004/* I/Web Console: notifyLayoutReady at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:02.930 1004-1004/* I/Web Console: null at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:02.930 1004-1004/* W/Web Console: The page at about:blank displayed insecure content from js-frame:notifyLayoutReady:0:%5B%5D.
                                                                       at null:1
02-16 14:23:03.050 1004-1004/* I/Web Console: setAttribute at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:03.050 1004-1004/* I/Web Console: chromecastAppId,FFCC6D19 at https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&*:7
02-16 14:23:03.050 1004-1004/* W/Web Console: The page at about:blank displayed insecure content from js-frame:setAttribute:0:%5B%22chromecastAppId%22%2C%22FFCC6D19%22%5D.
                                                                       at null:1`

**Comment by kaltura-hooks** [comment]
Hi @BartoszJarocki,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by BartoszJarocki** [comment]
Player never starts also on Android 5.1, Motorola Droid Turbo

**Comment by noamtamim** [comment]
Please test with v2.4.0.rc1 and MWE v2.40.
Which video are you trying to play?

**Comment by BartoszJarocki** [comment]
Sorry, what MWE is ?

**Comment by noamtamim** [comment]
mwEmbed, the html5 part of our player.
https://github.com/kaltura/mwEmbed

**Comment by BartoszJarocki** [comment]
Same with v2.4.0.rc1.

**Comment by giladna** [comment]
Hi @BartoszJarocki 
Need your help

since alot was changed
please take 2.5.16 edit the BasicPlayerDemo with your config and run it I am pretty sure it should be ok

if not please attach logs  or you config params with us so we will help you

**Comment by Nahueleti** [comment]
Hi @giladna Bartosz is no longer working for the project, I will help you out tomorrow

**Comment by giladna** [comment]
Seems not relevent any more
