### ISSUE TITLE
KHLSPlayer does not recover itself after pause/restart

### ISSUE THREAD

**Issue by filipecosta01** [kaltura/player-sdk-native-android#108]
Even though you have an implementation of recoverPlayer on KHLSPlayer, it's not possible to recover after pause/restart the fragment or activity.

That's what I've found:
**The selected player has a recover player method, obviously to recover after onPause/onResume**
```
@Override
    public void recoverPlayer() {
        mPlayer.recoverRelease();
    }
```

**The method references HLSPlayerViewController, which we cannot change (it's part of hlsplayersdk). It just save stuff on shared preferences and then we can retrieve things to set again**
```
@Override
    public void recoverRelease()
    {
        // Deserialize postion, playstate, and url
        SharedPreferences sp = getContext().getSharedPreferences("hlsplayersdk", Context.MODE_PRIVATE);
        mLastUrl = sp.getString("lasturl", "");
        mInitialPlayState = sp.getInt("playstate", 0);
        mStartupState = sp.getInt("startupstate", STARTUP_STATE_WAITING_TO_START);
		// ... more stuff here
        if (mRestoringState)
        {

            Thread t = new Thread( new Runnable()
            {
                @Override
                public void run() {

                    Log.i("VideoPlayer UI", " -----> Play " + mLastUrl);
                    setVideoUrl(mLastUrl, true, mInitialQualityLevel);
                    if (mInitialPlayState == STATE_PLAYING || mInitialPlayState == STATE_PAUSED) // The pause will happen immediately after playback resumes in initiatePlay()
                       

> Here we have a call to play state again, not a big deal, but...
						play();
                }
            });
            t.start();
```

**This guy calls another guy, postToInterface**

```
public void play() {

        postToInterfaceThread(new Runnable()
        {
            public void run()
            {
                requestState(FSM_PLAY);

            }
        });

    }
```

**This guy calls another guy, getInterfaceThreadHandler**
```
public static void postToInterfaceThread(Runnable runnable)
    {
        Handler handler = getInterfaceThreadHandler();
        if (handler != null)
        {
            handler.post(runnable);
        }
    }
```

**This here should not be null and it's not once we start playing (first time). But it is after onPause/onResume.**
```
public static Handler getInterfaceThreadHandler()
    {
        return (getInterfaceThread() != null) ? getInterfaceThread().getHandler() : null;
    }
```

**This currentController is null**
```
public static HLSUtilityThread getInterfaceThread()
    {
        return currentController != null ? currentController.mInterfaceThread : null;
    }
```

I've tested with your new release version and it's not working properly.
Do you guys can take a look at it?

**Comment by kaltura-hooks** [comment]
Hi @filipecosta01,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by itaykinnrot** [comment]
We now use ExoPlayer for that - should be fixed
