### ISSUE TITLE
Using PlayerViewController in a RecyclerView

### ISSUE THREAD

**Issue by qstuff** [kaltura/player-sdk-native-android#208]
Hi,

I want to use the PlayerViewController in a RecyclerView that holds 2 ViewHolder in which i added the PlayerViewController.

The idea is to create and initialize the PlayerViewController only once when creating the ViewHolder
and then change the entryId when i use the ViewHolder for other content.

This shall reduce the preparation time for the video since i do not need to initialize the player again and again (so the customer care support told me).

So my question is:

How can I change the entryID of an existing instance of  PlayerViewController, resp. of the KPPlayerConfig ?

**Comment by giladna** [comment]
There are 2 options available for you (you can find example in changeMediaDemo)

     1)      ChangeMedia stay with same config: mPlayer.changeMedia(newMediaId);

      2)Change configuration create new config that contains the new media
        mPlayer.changeConfiguration(newConfig);
