### ISSUE TITLE
mediaProxy.preferedFlavorBR doesn't work in Android WebView

### ISSUE THREAD

**Issue by Fr2eman** [kaltura/player-sdk-native-android#220]
## Problem 

Cannot change quality of video by using `mediaProxy.preferedFlavorBR`

## Expected result 

Quality doesn't change

## Device details

Samsung S2 (Android 5.1.1); 
Xiaomi mi4i(Android 6.0.1);

## Android Player SDK Version

Kaltura SDK version: '2.5.4'

## HTML5 Player Version

Version: v2.7
wid = 1858191
uiconf_id = 30743062
entry_id = 0_m3ecbkoa

## Logs:

Logs: http://codepad.org/4vNkTVZt 

## Steps to reproduce

Use code below

## Code

```
private PlayerViewController getPlayer() {
    if (mPlayer == null) {
		mPlayer = (PlayerViewController)findViewById(R.id.player);
		mPlayer.loadPlayerIntoActivity(this);
		KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com/html5/html5lib/v2.7/mwEmbedFrame.php", "30743062", "1858191").setEntryId("0_m3ecbkoa");
		config.setAutoPlay(true);
		mPlayPauseButton.setText("Pause");
		config.addConfig("mediaProxy.preferedFlavorBR", "900"); // this line doesn't change quality
		mPlayer.initWithConfiguration(config);
		if (mCastProvider != null) {
			mPlayer.setCastProvider(mCastProvider);
		}
		mPlayer.setOnKPErrorEventListener(this);
		mPlayer.setOnKPPlayheadUpdateEventListener(this);
		mPlayer.setOnKPFullScreenToggeledEventListener(this);
		mPlayer.setOnKPStateChangedEventListener(this);
	}
	return mPlayer;
}
```

## Sample

https://dl.dropboxusercontent.com/u/32611161/BasicPlayerDemo.zip

Kaltura SDK generate URL (for code above) http://cdnapi.kaltura.com/html5/html5lib/v2.7/mwEmbedFrame.php/p/1858191/sp/185819100/embedIframeJs/uiconf_id/30743062/entry_id/0_m3ecbkoa?iframeembed=true&wid=_1858191&uiconf_id=30743062&entry_id=0_m3ecbkoa&flashvars%5BautoPlay%5D=true&flashvars%5BmediaProxy.preferedFlavorBR%5D=900#localContentId=&nativeSdkDrmFormats=&nativeSdkAllFormats=dash,mp4,hls

But, when i use this URL in browser on desktop or phone default browser, it works, I even can change `flashvars%5BmediaProxy.preferedFlavorBR%5D` to another value it works

**Comment by kaltura-hooks** [comment]
Hi @Fr2eman,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by Fr2eman** [comment]
Hi @kaltura-hooks I updated ticket according requirements above

**Comment by giladna** [comment]
Hi @Fr2eman 

We will investigate it

anyway the entry you wrote does not have any video tracks init:

**Comment by Fr2eman** [comment]
Hi @giladna 

Actually there is not much info about your server infrastructure, so I don't understand why you use http://cfvod.kaltura.com server  Original video can be played by this link http://cdnapi.kaltura.com/html5/html5lib/v2.7/mwEmbedFrame.php/p/1858191/sp/185819100/embedIframeJs/uiconf_id/30743062/entry_id/0_m3ecbkoa?iframeembed=true&wid=_1858191&uiconf_id=30743062&entry_id=0_m3ecbkoa&flashvars%5BautoPlay%5D=true&flashvars%5BmediaProxy.preferedFlavorBR%5D=900#localContentId=&nativeSdkDrmFormats=&nativeSdkAllFormats=dash,mp4,hls  

So I'm not sure that I understand the problem, could you please explain it a little bit

**Comment by giladna** [comment]
you should use latest html5Lib 2.45 
you should also get latest SDK tag 2.5.17 that has support in tracks switching
for example you have it in uiconf: 35732951 

KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com", "35732951", "1858191").setEntryId("0_m3ecbkoa");

I will update regarding your initial request later

**Comment by Fr2eman** [comment]
> you should use latest html5Lib 2.45 
> you should also get latest SDK tag 2.5.17 that has support in tracks switching
> for example you have it in uiconf: 35732951

I updated html5lib (2.45) and KalturaSDK (2.517).
Why can't i use own uiconf(30743062)?

> KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com", "35732951", "1858191").setEntryId("0_m3ecbkoa");

Is it ok to use Url http://cdnapi.kaltura.com without /html5/html5lib/v2.45/mwEmbedFrame.php path ?

> if you open the android project KalturaDemos in your studio 
> you will see several demos for your use

KalturaDemos haven't examples for change quality.

**Comment by giladna** [comment]
if you upgrade the player so you can use this uiconf, no problem

http://cdnapi.kaltura.com  is OK

I will tag 2.5.18 today you will be able yo use :config.addConfig("mediaProxy.preferedFlavorBR", "900");

in this version

**Comment by Fr2eman** [comment]
> if you upgrade the player so you can use this uiconf, no problem

i updated kaltura sdk to version 2.5.18
but i still can't change quality.

this is my config:
```
KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com",
                "35732951", "1858191").setKS(ks).setEntryId("0_m3ecbkoa").addConfig("mediaProxy.preferredFlavorBR", "397");
config.setAutoPlay(false);
config.addConfig("controlBarContainer.plugin", "true");
config.addConfig("topBarContainer.plugin", "true");
config.addConfig("largePlayBtn.plugin", "true");
config.addConfig("loadingSpinner.plugin", "true");
config.addConfig("sourceSelector.plugin", "true");
```
this screenshot kaltura player from my app:
https://dl.dropboxusercontent.com/u/32611161/Screenshot_2016-07-18-13-38-53.png

I changed _mediaProxy.preferredFlavorBR_ different values: 100, 300, 900, 4000. 
But quality always have value: Auto

Also, AutoPlay always works, even when i use 
config.setAutoPlay(false);   or   config.addConfig("autoPlay", "false");
Do i create a new ticket?
