### ISSUE TITLE
config.addConfig("mediaProxy.preferredFlavorBR", "600"); doesn't work

### ISSUE THREAD

**Issue by Fr2eman** [kaltura/player-sdk-native-android#227]
## Problem

Cannot change quality of video by using config.addConfig("mediaProxy.preferredFlavorBR", "600")

## Expected result

Quality doesn't change, always it has value is Auto

## Device details

Samsung S2 (Android 5.1.1); 
Xiaomi mi4i(Android 6.0.1);

## Android Player SDK Version

Kaltura SDK version: '2.5.18'

## HTML5 Player Version

Version: v2.45
wid = 1858191
uiconf_id = 35732951
entry_id = 1_900w36sk

## Logs 

Logs http://codepad.org/oaVMRjk5

## Steps to reproduce

Use code below

## Code

```
KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com",
                "35732951", "1858191").setKS(ks).setEntryId("1_900w36sk");
        config.setAutoPlay(false);
        config.addConfig("controlBarContainer.plugin", "true");
        config.addConfig("topBarContainer.plugin", "true");
        config.addConfig("autoPlay", "false");
        config.addConfig("largePlayBtn.plugin", "true");
        config.addConfig("loadingSpinner.plugin", "true");
        config.addConfig("sourceSelector.plugin", "true");

        config.addConfig("sourceSelector.displayMode", "bitrate");
        config.addConfig("mediaProxy.preferredFlavorBR", "600");

        kalturaPlayer.initWithConfiguration(config);
        kalturaPlayer.registerReadyEvent(new VideoReadyListener());
```

## Sample

this screenshot kaltura player from my app:
https://dl.dropboxusercontent.com/u/32611161/Screenshot_2016-07-20-10-28-20.png

Kaltura SDK generate URL:
"kWidget: Kaltura HTML5 Version: 2.45 ( iframe ) ", source: http://cdnapi.kaltura.com/html5/html5lib/v2.45/mwEmbedLoader.php?&wid=_1858191&uiconf_id=35732951&p=1858191&iframeServer=true

I changed mediaProxy.preferredFlavorBR different values: 100, 300, 900, 4000. 
But quality always have value: Auto

Also, AutoPlay always works, even when i use 
config.setAutoPlay(false); or config.addConfig("autoPlay", "false");
Should I create another ticket for autoplay problem?

**Comment by kaltura-hooks** [comment]
Hi @Fr2eman,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Hi,
Please pull 2.5.18 again it was tagged twice and I assume that you took the first version which we had issue with Travis. 

Wc can see you have 3 tracks and that for 600 we select the preferred 0.68Mbit:
0 = auto-0
1 =  0.68Mbit
2 = 0.48Mbit

when you use:      config.addConfig("mediaProxy.preferredFlavorBR", "600");

you will see in log that index 1 (680) was selected:
07-20 22:17:21.532 10000-10000/com.kaltura.basicplayerdemo D/TracksManager: preferred bitrate selected = TrackFormat{index=1, trackType=VIDEO, trackId='0', bitrate=679936, channelCount=-1, sampleRate=-1, height=360, width=640, mimeType='video/avc', trackLabel='640x360, **0.68Mbit**, 0', language='null', adaptive=false}

Regarding AutoPlay:

I have tested it on our BasicDemoApp in the KalturaDemos 
with the config you gave (ks was not needed) and both options work fine please check again after retaking 2.5.18 

// config.addConfig("autoPlay", "false");
//config.setAutoPlay(false);

**Comment by giladna** [comment]
Sorry for making you doing it twice.

Please update if need some more assitance

**Comment by Fr2eman** [comment]
> We should add it soon hopefully.

Thanks

> I have tested it on our BasicDemoApp in the KalturaDemos 
> with the config you gave (ks was not needed) and both options work fine

I can't disable autoplay

**Comment by giladna** [comment]
did you try in DemoApp?

**Comment by Fr2eman** [comment]
> did you try in DemoApp?

yes, but config.setAutoPlay doesn't work when i use config.addConfig("mediaProxy.preferredFlavorBR", "600");  

without **config.addConfig("mediaProxy.preferredFlavorBR", "600");** I can disable autoplay

**Comment by giladna** [comment]
Fixed in FEM-641
will be  merged to next version 2.5.21

**Comment by Fr2eman** [comment]
> Fixed in FEM-641

I checked FEM-641 and FEM_641_1
Problem still exists

**Comment by giladna** [comment]
fixed :https://github.com/kaltura/player-sdk-native-android/releases/tag/v2.5.21
