### ISSUE TITLE
config.addConfig("mediaProxy.preferredFlavorBR", "700"); still doesn't work

### ISSUE THREAD

**Issue by Fr2eman** [kaltura/player-sdk-native-android#231]
## Problem

Cannot change quality of video by using config.addConfig("mediaProxy.preferredFlavorBR", "700")

## Expected result

Quality doesn't change, always it has value is Auto

## Device details

Samsung S2 (Android 5.1.1); 
Xiaomi mi4i(Android 6.0.1);

## Android Player SDK Version

Kaltura SDK version: '2.5.21.2'
I tried version 2.5.21 and 2.5.21.1

## HTML5 Player Version

Version: v2.45
wid = 1858191
uiconf_id = 35732951
entry_id = 0_86yighs7

## Steps to reproduce

Use code below

## Logs

http://codepad.org/tu6e3sKy  

## Code

```
KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com",
                "35732951", "1858191").setEntryId("0_86yighs7");
        config.addConfig("controlBarContainer.plugin", "true");
        config.addConfig("topBarContainer.plugin", "true");
        config.addConfig("largePlayBtn.plugin", "true");
        config.addConfig("loadingSpinner.plugin", "true");
        config.addConfig("sourceSelector.plugin", "true");

        config.addConfig("sourceSelector.displayMode", "bitrate");
        config.addConfig("mediaProxy.preferredFlavorBR", "700");

        kalturaPlayer.initWithConfiguration(config);
        kalturaPlayer.registerReadyEvent(new VideoReadyListener());
```

## Sample

this screenshot kaltura player from my app:
https://dl.dropboxusercontent.com/u/32611161/Screenshot_2016-07-26-11-37-11.png

Kaltura SDK generate URL:
"kWidget: Kaltura HTML5 Version: 2.45 ( iframe ) ", source: http://cdnapi.kaltura.com/html5/html5lib/v2.45/mwEmbedFrame.php/p/1858191/uiconf_id/35732951/entry_id/0_86yighs7?entry_id=0_86yighs7&wid=_1858191

I changed mediaProxy.preferredFlavorBR different values: 100, 300, 900, 4000. 
But quality always have value: Auto
In logs I see the line  
```
07-26 11:34:35.551 30471-30471/com.hilti.mobile.hiltipulse D/TracksManager: switchTrackByBitrate : VIDEO preferredBitrateKBit : 700
07-26 11:34:35.555 30471-30471/com.hilti.mobile.hiltipulse D/TracksManager: preferred bitrate selected = TrackFormat{index=1, trackType=VIDEO, trackId='0', bitrate=686080, channelCount=-1, sampleRate=-1, height=360, width=640, mimeType='video/avc', trackLabel='640x360, 0.69Mbit, 0', language='null', adaptive=false}
07-26 11:34:35.555 30471-30471/com.hilti.mobile.hiltipulse D/TracksManager: switchTrack for VIDEO newIndex = 1
```

**Comment by kaltura-hooks** [comment]
Hi @Fr2eman,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Thanks
I can see that your selection is done:
{code}
07-27 11:20:39.695 32534-32534/com.kaltura.basicplayerdemo D/TracksManager: switchTrackByBitrate : VIDEO preferredBitrateKBit : 700
07-27 11:20:39.696 32534-32534/com.kaltura.basicplayerdemo D/TracksManager: preferred bitrate selected = TrackFormat{index=1, trackType=VIDEO, trackId='0', bitrate=686080, channelCount=-1, sampleRate=-1, height=360, width=640, mimeType='video/avc', trackLabel='640x360, 0.69Mbit, 0', language='null', adaptive=false} excact bitrate = 686080
{code}

**Comment by Fr2eman** [comment]
> I can see that your selection is done:
> so it is only ui issue
> and as I said I am not sure it is a bug since the engine will keep working as auto afterwards

But it's not good
Should I create another ticket for this problem?

**Comment by giladna** [comment]
I am releasing 2.5.24

check it on it
i fixed the values so you get to the real bitrates as in the stream
if you have native ui for this you may be able to control on it as  you like

**Comment by giladna** [comment]
you can also look at the basicDemoApp with your params and compare

**Comment by Fr2eman** [comment]
> i fixed the values so you get to the real bitrates as in the stream
> if you have native ui for this you may be able to control on it as you like

How can i get the video stream which can be player with my own player?
Can I use default android media player? Any samples?

**Comment by giladna** [comment]
there is API to the server where you can query it
Not in my domain 
sorry

**Comment by CAMOBAP795** [comment]
@giladna I also interesting in it, maybe you can point us to some server documentation?

**Comment by giladna** [comment]
@CAMOBAP795 
Think this is entry point http://www.kaltura.com/api_v3/testmeDoc/

Native UI is like you can control the player via android native conrols like play/pause/seek operations and not via the webview

you can see example for both options in:
https://github.com/kaltura/player-sdk-native-android/tree/develop/KalturaDemos/BasicPlayerDemo

**Comment by jessp01** [comment]
Hello,

You can see the API documentation here:
https://developer.kaltura.com/api-docs/#/Overview

You may also find this useful as a starting point for working with the Kaltura Server API:
https://developer.kaltura.com/recipes/

If you have specific questions, please free to post them at forum.kaltura.org.
Also, the Kaltura Server is FOSS project licensed as AGPLv3 and its source is fully accessible via https://github.com/kaltura/server.

**Comment by CAMOBAP795** [comment]
Thanks @giladna @jessp01 

I already saw these links, there is no API to get stream in some common format like http, hls or rtp, or usual mp4 file

So there is no way to use native player, correct me if I'm wrong

**Comment by giladna** [comment]
@CAMOBAP795 
This looks like what you need
https://knowledge.kaltura.com/faq/how-retrieve-metadata-media-entry-using-api

**Comment by Fr2eman** [comment]
@giladna 
I can get video stream (use http://www.kaltura.com/api_v3/index.php?service=media&action=get&entryId={yourentryId}&ks={ks})
But how can i get a video stream of the desired quality?

**Comment by jessp01** [comment]
Hello @Fr2eman,

By "stream" do you mean the flavor URL?
Each entry consists of one or more [typically more] flavors, depending on your transcoding profile.
If that's what you mean, then the API service you want is called flavorAsset and for the URL, the action is getUrl.
You need to pass along the flavorId, which you can get from calling the list() action, passing along an entryId.

If this is not what you wanted, can you please reiterate exactly what you need?

Thanks,

**Comment by Fr2eman** [comment]
> By "stream" do you mean the flavor URL?

Yes, I mean the flavor URL
I need select quality 360 HQ, how to find out which flavor Id corresponds to quality 360 HQ

**Comment by CAMOBAP795** [comment]
The same question form me

@jessp01 @giladna where can I found mapping between flavorId and corresponding quality?

**Comment by jessp01** [comment]
@CAMOBAP795, @Fr2eman,

When you call flavorAsset->list(), passing an entry ID, you will get all flavours created for this entry.
Each of these has an ID, which you can get the name for by calling flavorParams->get() passing as id, the flavorParamsId value you got from making the flavorAsset->list() call.

If you know what flavorParamsId you are interested in, you can simply call flavorAsset->list() with the KalturaFlavorAssetFilter, passing entryIdEqual=$YOUR_ENTRY flavorParamsId=$DESIRED_FLAVOR_PARAM_ID

**Comment by jessp01** [comment]
Closing this one. @Fr2eman and @CAMOBAP795, for additional questions on this flavor.* APIs, please post on forum.kaltura.org.
