### ISSUE TITLE
Tried to play video that exceeded baseline profile (77 > 66), aborting!

### ISSUE THREAD

**Issue by mchakroun** [kaltura/player-sdk-native-android#34]
I'm getting this error while the same embed is working fine with browser:
01-28 16:23:01.376  27724-28016/com.kaltura.kalturaplayertoolkit I/bool HLSPlayer::InitSources()﹕ Validating H.264 AVC profile level...
01-28 16:23:01.376  27724-28016/com.kaltura.kalturaplayertoolkit E/bool HLSPlayer::InitSources()﹕ Tried to play video that exceeded baseline profile (77 > 66), aborting!
01-28 16:23:01.376  27724-28016/com.kaltura.kalturaplayertoolkit E/void HLSPlayer::PostError(int, char const*)﹕ Posting error -106 : Tried to play video that exceeded baseline profile. Aborting.

Regards

**Comment by InbarItay** [comment]
Hi,
Which device are you using if I may ask?

What happens is that the stream you are trying to play is an HLS stream. HLS streams have the option of profiles - which basically defines the quality of the video being streamed.
According to the official Google documentation Android devices don't support HLS streams with profiles which exceed the baseline profile:
http://developer.android.com/guide/appendix/media-formats.html

So at the moment the app won't support any stream which doesn't have any baweline profile tracks.

With that being said (although what is written in the Google documentation) we've discovered that there are some devices which actually do support this feature.

We are currently working on this issue and will try to provide a solution.
We will update as soon as this matter is resolved.

**Comment by mchakroun** [comment]
.thank you for the fast response. I'am using a Samsung note 2, and yes it's an HLS stream, what I don't understand is why the same stream URL is working on chrome browser and not with the SDK.
Regards

**Comment by InbarItay** [comment]
You mean a desktop browser or your mobile device's browser?

**Comment by mchakroun** [comment]
Mobile Browser
