### ISSUE TITLE
Can't play this video

### ISSUE THREAD

**Issue by rajendrabohra** [kaltura/player-sdk-native-android#4]
Hello, 
I am implementing Kaltura player sdk in one of my project for playing live stream data. I have downloaded this library project and followed steps given in this http://knowledge.kaltura.com/kaltura-player-sdk-android  link . I am getting "Can't play this video" dialog. While the video given in the link is playing fine in browser.
getting this error "MediaPlayer(20483): error (1, -1004)"
Please help me if I am missing something.

**Comment by itaykinnrot** [comment]
Hi @orenk86 - we've update out SDK - please get the latest from Master and follow the readme file - you should be ok.
