### ISSUE TITLE
Can not seek 

### ISSUE THREAD

**Issue by hoangtu23** [kaltura/player-sdk-native-android#53]
I've tried with release 1.7.
When video is playing, can not seek to desire position in video.
Someone please take a look & give me a guide to fix.

Thanks,
--
Tu

**Comment by hoangtu23** [comment]
@MichalRadwantzor @InbarItay 
Please take a look when you have time

**Comment by InbarItay** [comment]
Hi,
Which version of the Kaltura javascript player are you using?

**Comment by hoangtu23** [comment]
Hi @InbarItay,
I used same as Kaltura v1.7
https://github.com/kaltura/player-sdk-native-android/blob/master/playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java

**Comment by hoangtu23** [comment]
Any update?

**Comment by hoangtu23** [comment]
It was fixed by new release (1.8).
Close this issue.
