### ISSUE TITLE
Video is not shown but audio is being streamed successfully.

### ISSUE THREAD

**Issue by taskinkemal** [kaltura/player-sdk-native-android#55]
I followed the steps in http://knowledge.kaltura.com/kaltura-player-sdk-android however, when I press the play icon video starts with a black screen.

By the way, in the link above there is a method called "addComponents" but it does not exist in the library. What i found is a "setComponents" method:

mPlayerView.setComponents("http://cdnapi.kaltura.com/p/1937571/sp/193757100/embedIframeJs/uiconf_id/29215882/partner_id/1937571?iframeembed=true&playerId=kaltura_player_1432632971&entry_id=1_9ukxi0pe&flashvars[akamaiHD.loadingPolicy]=preInitialize&flashvars[akamaiHD.asyncInit]=true&flashvars[streamerType]=hdnetwork");

Above is the streaming option. There is another problem in the progress option: When I press play, video does not play at all and freezes at the first scene.

**Comment by itaykinnrot** [comment]
Hi @taskinkemal - we update our SDK please follow the readme file and you should be ready to go.
Thanks,
