### ISSUE TITLE
Not able to start streaming videos

### ISSUE THREAD

**Issue by filipecosta01** [kaltura/player-sdk-native-android#92]
The current flow takes the steps:

We can retrieve the uiConfId and partnerId
We can start the player using a new instance of PlayerViewController, Including the params to instantiate it:
Domain: https://cdnapisec.kaltura.com
uiConfId
partnerId

Including the config params:
entryId
ks (Kaltura Session Id)

And call the method initWithConfiguration on PlayerViewController. The player is displayed on the screen, but it's not possible to play it.

Analyzing the logs, we checked an error with network connection (even though the device's connection is ok):

I/NuCachedSource2: currently network is disconnected (error -1), it will be reconnected in 10 retries
E/NuCachedSource2: source returned error -1, 10 retries left

And it goes until the 10th retry, when an exception is thrown:

E/ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:272)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:145)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Caused by: java.io.IOException: Failed to instantiate extractor.
at android.media.MediaExtractor.nativeSetDataSource(Native Method)
at android.media.MediaExtractor.setDataSource(MediaExtractor.java:143)
at android.media.MediaExtractor.setDataSource(MediaExtractor.java:117)
at com.google.android.exoplayer.FrameworkSampleSource.prepare(FrameworkSampleSource.java:136)
at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:281)

One of the many retries attempts logs:

I/NuCachedSource2: readAt: mIsMetadataRetriever == 0
V/NuCachedSource2: onRead
D/NuCachedSource2: readInternal - late!!!
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onRead
V/NuCachedSource2: readInternal offset 0 size 4
I/NuCachedSource2: seek : hint hits! 0 -> mAVminOffset = 0
V/NuCachedSource2: deferring read
V/NuCachedSource2: onFetch
V/NuCachedSource2: fetchInternal
V/MediaHTTP: reconnectAtOffset offset=0
V/MediaHTTP: connection established
E/NuCachedSource2: source returned error -1, 2 retries left
E/NuCachedSource2: source returned error -1, 2 retries left

The video never starts streaming, even though we are able to play the Demo video, following the same configuration as below:

// Kaltura Player Demo Configuration
mConfig = new KPPlayerConfig("http://kgit.html5video.org/tags/v2.39.rc8/mwEmbedFrame.php", "32855491", "1424501");
mConfig.setEntryId("1_32865911");

What could be wrong?

**Comment by kaltura-hooks** [comment]
Hi @filipecosta01,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by filipecosta01** [comment]
Guys, if anyone can take a look into this, I would really appreciate it.
Thano you in advance.

**Comment by filipecosta01** [comment]
Guys, if anyone can take a look into this, I would really appreciate it.
Thano you in advance.

**Comment by nissopa** [comment]
@filipecosta01 Hi,
Did you close the issue because it already solved, or do you need my help?

Thanks,

**Comment by filipecosta01** [comment]
Hi,
Already solved it. We might missed the Android Profile in KMC.
Maybe, just to improve that, you could associate a message to it, instead
of keep loading forever. What do you think about it?

**Comment by nissopa** [comment]
We are working now on error handling, It will be ready in a few days

Thanks,
